- hosts: master
  become: yes
  tasks:
    - name: Initialize the cluster
      shell: kubeadm init --apiserver-advertise-address=192.168.56.70 --pod-network-cidr=10.244.0.0/16

    - name: Setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown vagrant:vagrant /home/vagrant/.kube/config

    - name: Install Pod Network
      shell: KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f https://calico-v3-25.netlify.app/archive/v3.25/manifests/calico.yaml

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
